# Generated by Django 2.1.4 on 2018-12-11 11:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tipoCocina', models.CharField(max_length=200)),
                ('tiempoPreparacion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
            managers=[
                ('platos', django.db.models.manager.Manager()),
            ],
        ),
    ]
